### ISSUE TITLE
Bookmarks Cards not working

### ISSUE THREAD

**Issue by styxlab** [TryGhost/gatsby-starter-ghost#102]
After importing Ghost blog posts that use the great v3 feature "bookmark cards", they come out completely scrambled on this theme.

This is probably just a styling issue, but could you please support all standard Ghost elements (like bookmark cards) in this theme?

**Comment by AileenCGN** [comment]
Happy to take PRs here. There's a good CSS example already [here](https://ghost.org/docs/api/v3/handlebars-themes/editor/#bookmark-card), which would probably only need porting over to the styles in this repo.

**Comment by styxlab** [comment]
PR #104 as requested.
