### ISSUE TITLE
Add support for Casper font styles

### ISSUE THREAD

**Issue by styxlab** [TryGhost/gatsby-starter-ghost#103]
I'm not sure if this is a bug or a feature, but the font types/styles provided by the original Casper theme are more pronounced and much cleaner:

- Original Casper Style
![Original Casper Style](https://api.atmolabs.org/v1/assets/images/casper-original.png)

- Gatsby Casper Style (this repo)
![Gatsby Casper Style](https://api.atmolabs.org/v1/assets/images/gatsby-casper.png)

If you look a the details, you'll see a huge difference! Can you please make the original style available here?

**Comment by AileenCGN** [comment]
The Gatsby Starter repo is not intended to be like the default Casper theme for Ghost, but should rather give you a good starting point to style it your own way. So yes, the difference is intentional and not a bug.

I will close, as it's not an issue 😃
