### ISSUE TITLE
Found a vulnerability with minimist in gatsby-plugin-ghost

### ISSUE THREAD

**Issue by JesusWisord** [TryGhost/gatsby-starter-ghost#110]
I've just pushed my project to Github and this showed up

![Captura de Pantalla 2020-03-23 a la(s) 9 13 19](https://user-images.githubusercontent.com/29292926/77331843-e34d6700-6ce6-11ea-9c9b-1d719050ae4d.png)

**Comment by aileen** [comment]
I'm not able to reproduce this any more. Assuming, this is fixed by now.
