### ISSUE TITLE
GraphQL error on start

### ISSUE THREAD

**Issue by mquandalle** [TryGhost/gatsby-starter-ghost#17]
Hello,

When I `yarn install`, `yarn dev` this project I encounter the following error on Linux:

```
error GraphQL Error Unknown field `childImageSharp` on type `File`

  file: /home/mquandalle/gatsby-starter-ghost/src/components/common/Layout.js

   1 |
   2 |             query GhostSettings {
   3 |                 allGhostSettings {
   4 |                     edges {
   5 |                         node {
   6 |                             ...GhostSettingsFields
   7 |                         }
   8 |                     }
   9 |                 }
  10 |                 file(relativePath: {eq: "ghost-icon.png"}) {
> 11 |                     childImageSharp {
     |                     ^
  12 |                         fixed(width: 30, height: 30) {
  13 |                             ...GatsbyImageSharpFixed
  14 |                         }
  15 |                     }
  16 |                 }
  17 |             }
  18 |
```

Is that expected?

**Comment by gargol** [comment]
Hey @mquandalle! Was running into the same issue when running the repo at 4a5ebda version, but after pulling the latest changes from master and running `yarn && yarn dev` worked perfectly. Let me know if the same error happens for you after an update :)

**Comment by mquandalle** [comment]
Indeed it works with the latest changes from `master`, is that what `gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git` is supposed to do or is it possible that running this command will pull an outdated version of this repository?

**Comment by AileenCGN** [comment]
The moment you run `gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git` you create a snapshot of the repo. Unfortunately yours contained this issue 😔  

Updating it like @gargol recommended downloaded the fix for it.

Closing this issue, as it's solved now.
