### ISSUE TITLE
Excerpts on front page are clipped on mobile devices

### ISSUE THREAD

**Issue by MarcoZehe** [TryGhost/gatsby-starter-ghost#192]
### Issue Summary

On the front page of the sample, when viewed on an iPhone, the text of the post excerpts is clipped. Does not word wrap and looks incomplete. This is on the post-card-excerpt items.

### To Reproduce

1. Build the sample
2. View it on an iPhone or iPod Touch in portrait mode.

Expected the text to be visible, possibly wrapped to multiple lines.

### Technical details:

* Ghost Version: 3.17.1
* Gatsby Version: 2.22.latest
* Node Version: 10.12
* OS: iOS 13.5

**Comment by aileen** [comment]
Hey there @MarcoZehe 

This starter is intended to be a "starting" point and is by all means nowhere to complete. This starter uses only a bare minimum of styles and markup so that everyone can develop into the direction they desire.

Hope that makes sense!
😃
