### ISSUE TITLE
Remove quotes from the alt attribute

### ISSUE THREAD

**Issue by godofredoninja** [TryGhost/gatsby-starter-ghost#21]
😄  I'm playing with ghost and gatsby I'm very excited

— This is the result that comes by default

```html
<img class="site-logo" src="https://static.ghost.org/v1.0.0/images/ghost-logo.svg" alt="{site.title}">
```
— And this is resolved by removing the quotes from the alt attribute of the image. 😄 
https://github.com/TryGhost/gatsby-starter-ghost/blob/87761f6b99d1a2ea334ea967160ab54cfac5955c/src/components/common/Layout.js#L43-L44

**Comment by AileenCGN** [comment]
Hey @godofredoninja 👋 

Thanks for the report and good 🎣 

Fixing this quickly 😊
