### ISSUE TITLE
upgrading to 2.23.22 produces a flurry of errors

### ISSUE THREAD

**Issue by timfee** [TryGhost/gatsby-starter-ghost#223]
Hi there, 

When I did an upgrade to the newest Ghost, I was totally bricked.

Reverting back to .21 fixed it.

Attaching logs
[yikes.log](https://github.com/TryGhost/gatsby-starter-ghost/files/4887975/yikes.log)

**Comment by dMcCaffree** [comment]
Having the same issue. I pulled from the latest in the repo.

**Comment by Tsatsi** [comment]
I'm having the same issue.  I pulled the latest repo. When I run `gatsby develop` I get a lot of graphQL query errors.

**Comment by thcheung** [comment]
I am new to gatsby-start-ghost. I am having the same issue when I clone the latest repo. I downloaded the previous repo v2.23.2 and works for me.

**Comment by aileen** [comment]
Did you use the config as recommended it the README?
<img width="879" alt="image" src="https://user-images.githubusercontent.com/8037602/93157917-46342e00-f75f-11ea-8b3b-038c303bcab5.png">


What exactly were those errors? It's hard to debug and reproduce without further information...
