### ISSUE TITLE
Data schema stub

### ISSUE THREAD

**Issue by JasonMillward** [TryGhost/gatsby-starter-ghost#227]
### Issue Summary

Data schema stub is making its way to the build output. 

> This is a data schema stub for Gatsby.js and is not used. It must exist for builds to function

This may belong more in `gatsby-source-ghost` but I'm not familiar enough with either code base to make that judgement call.

### To Reproduce

1. `gatsby build` with a valid contentApiKey

You can also see it on https://gatsby.ghost.org/

<img width="339" alt="image" src="https://user-images.githubusercontent.com/1149781/87666567-fc9f8500-c7a7-11ea-9edf-f249bec17097.png">

### Technical details:

```
    "@tryghost/helpers": "1.1.27",
    "@tryghost/helpers-gatsby": "1.0.31",
    "cheerio": "1.0.0-rc.3",
    "core-js": "^3.6.5",
    "gatsby": "2.23.20",
    "gatsby-awesome-pagination": "0.3.6",
    "gatsby-image": "2.4.12",
    "gatsby-plugin-advanced-sitemap": "1.5.5",
    "gatsby-plugin-catch-links": "2.3.10",
    "gatsby-plugin-fathom": "^1.1.0",
    "gatsby-plugin-feed": "2.5.10",
    "gatsby-plugin-force-trailing-slashes": "1.0.4",
    "gatsby-plugin-manifest": "2.4.17",
    "gatsby-plugin-offline": "3.2.16",
    "gatsby-plugin-prefetch-google-fonts": "^1.4.3",
    "gatsby-plugin-react-helmet": "3.3.9",
    "gatsby-plugin-sharp": "2.6.17",
    "gatsby-source-filesystem": "2.3.18",
    "gatsby-source-ghost": "4.0.5",
    "gatsby-transformer-sharp": "2.5.10",
```

**Comment by kjprince** [comment]
Seeing the same issue

**Comment by MakanWG** [comment]
Not sure if it is new though ? When you search the exact terms on google you can find blogs as old as 2018

**Comment by vitalbeach** [comment]
@MakanWG it's popped up sometime in the past 4-5 months. i didn't run into this issue until i had to repush my site last week.

**Comment by srivastavarnav** [comment]
+1 same issue

**Comment by endymion1818** [comment]
+1 same issue here[https://freebabylon5.com](https://freebabylon5.com)

**Comment by endymion1818** [comment]
I fixed in my repo by adding a filter to my index template: 

```    
allGhostPost(
        sort: { order: DESC, fields: [published_at] },
        limit: $limit,
        skip: $skip
        filter: {
            authors: {
                elemMatch: {
                    id: {ne: "179e06da7ae846929bb30f19f3e82ecb"}
                }
            }
        }
```

You can view that code here: https://github.com/endymion1818/freeb5-frontend-ghost/blob/master/src/templates/index.js#L60

Please let me know if this works for you, if so I'll submit a PR to this repo.

**Comment by JasonMillward** [comment]
Works for me, hopefully it's a temporary solution :)

**Comment by vitalbeach** [comment]
> I fixed in my repo by adding a filter to my index template:
> 
> ```
> allGhostPost(
>         sort: { order: DESC, fields: [published_at] },
>         limit: $limit,
>         skip: $skip
>         filter: {slug: {ne: "data-schema"}}
> )
> ```
> 
> You can view that code here: https://github.com/endymion1818/freeb5-frontend-ghost/blob/master/src/templates/index.js#L60

404 and bad syntax if I try to copy. any help?

**Comment by vitalbeach** [comment]
to be fair, if i eventually post enough, this will be hidden. i'm not super worried about it.

**Comment by JasonMillward** [comment]
It's a one liner [here is my commit](https://github.com/JasonMillward/jcode-static/commit/d01f1af544ac22a4d727dda23f4ba7f41729fca3), and I think posting more will only push it down the pages, not remove it completely. 

Is the Android issue with Ghost or with Gatsby?

**Comment by vitalbeach** [comment]
i'm now running into all kinds of errors now, and I'm not sure why. I'm going to pull my repo again in the next few days to start over.

the android issue is related to them not updating the app to accept api v3 i think.
https://github.com/TryGhost/Ghost-Android/issues/45

**Comment by vitalbeach** [comment]
@JasonMillward your fix worked for me. thank you!
