### ISSUE TITLE
Custom XML Sitemap plugin

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/gatsby-starter-ghost#23]
Create custom XML Sitemap plugin which we depend on, and mimics Ghost native sitemaps.

**Comment by rishabhgrg** [comment]
To support SEO, we should generate a sitemap.xml, which we currently generate using `gatsby-plugin-sitemaps`. 

Demo: https://gatsby.ghost.io/sitemap.xml

While the above sitemap does its job, the sitemaps we generate right now in Ghost setup is really good, and nothing equivalent really exists in gatsby as such. It generates XML sitemaps for different content formats, brought together in a main XML file and served through an XSL template. 

Demo: https://blog.ghost.org/sitemap.xml

The sitemap structure looks like:

Index
Posts
Pages (contains home)
Tags
Authors
These should be generated once and saved in the filesystem, and updated on relevant changes. 

Goal is to create a custom gatbsy XML sitemap plugin which follows above pattern and on which the starter depends on, but can be used by others as well.

**Comment by AileenCGN** [comment]
We published the plugin here: https://github.com/TryGhost/gatsby-plugin-advanced-sitemap
