### ISSUE TITLE
This repo is currently broken

### ISSUE THREAD

**Issue by bernhardc** [TryGhost/gatsby-starter-ghost#232]
Altough this problem is already being discussed in #223 , I opened this issue so newcomers like me won't wonder why a fresh install of this repo isn't working at the moment.

For a fix refer to this post: https://github.com/TryGhost/gatsby-starter-ghost/issues/223#issuecomment-662194062

**Comment by daviddarnes** [comment]
Please don't create duplicate issues, while your intentions were decent this produces deeper rabbit roles for people to navigate. The original issue is sufficient
