### ISSUE TITLE
BUG: Fresh install does not work - new build is broken

### ISSUE THREAD

**Issue by Rubix982** [TryGhost/gatsby-starter-ghost#233]
### Issue Summary

Using the fresh install of the `gatsby-ghost-starter` pack does not work, and the issue has to do with `graphql`.
I've tried both ways for the installation. I've used,

```
# With Gatsby CLI
gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git
```

And 

```
# From Source
git clone https://github.com/TryGhost/gatsby-starter-ghost.git
cd gatsby-starter-ghost
yarn
```

Both give out the same set of error messages. 

The error message is quite long. In the terminal, I see an ending of this kind of output - see screenshot,

![image](https://user-images.githubusercontent.com/41635766/88473507-b8467e80-cf37-11ea-90af-4f9c53034595.png)

Opening up the locally hosted server, I see the following error messages,

![image](https://user-images.githubusercontent.com/41635766/88473514-c85e5e00-cf37-11ea-85b4-769d1d64c211.png)

The complete error log can be seen at [this gist](https://gist.github.com/Rubix982/003dcfb3e9ee88c5e26acafe408fecb5).

For context, I did try that `ghost-cli` was working perfectly on my machine, and ran the following commands to test a local install and reproduction of ghost,

```
npm install ghost-cli -g
ghost install local
```

Which gave me a local hosted server, and was working perfectly fine as expected. 

For context, I did indeed pull a clone about 30 minutes ago, so my `.ghost.json` is as expected,

```
{
  "development": {
    "apiUrl": "https://gatsby.ghost.io",
    "contentApiKey": "9cc5c67c358edfdd81455149d0"
  },
  "production": {
    "apiUrl": "https://gatsby.ghost.io",
    "contentApiKey": "9cc5c67c358edfdd81455149d0"
  }
}
```

Looking at errors, it has something to do with graphql...?

### To Reproduce

Just install a fresh build,

```
# With Gatsby CLI
gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git
gatsby develop
```

And 

```
# From Source
git clone https://github.com/TryGhost/gatsby-starter-ghost.git
cd gatsby-starter-ghost
yarn
gatsby develop
```

### Technical details:

* Ghost Version: `1.14.1`
* Gatsby Version: `2.24.4`
* Node Version: `v10.19.0`
* OS: `kubuntu`, `Linux kubuntu-saif 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Thanks for your time!

**Comment by dyaskur** [comment]
I have the same issue with develop command, but build and serve is working

**Comment by ogrotten** [comment]
@Rubix982 You might kick that error paste over to a Gist or pastebin.ca. 

I have the same issue. Server appears to be working, but the content errors out.

**Comment by Rubix982** [comment]
Alright, @ogrotten . I was unsure if pasting here or somewhere else would be better option, so I did here instead. Lemme make a gist and update. Thanks!

@dyaskur I cannot, what did you set `siteUrl` to, exactly?

**Comment by ogrotten** [comment]
@Rubix982 thanks that helps a lot. 😁

Additionally, I went back to https://github.com/TryGhost/gatsby-starter-ghost/tree/61620ba, a maintenance commit from 2 weeks ago and it works without issue.

On that page go to Code > Download ZIP. Put the zip in your dir of choice (like your own inited repo). Then go `yarn` and then `gatsby develop`.

**Comment by Rubix982** [comment]
@ogrotten woooohoooooo, it actually works! I thought I was doing something wrong this whole time! xD

So there's something in the newest commit that breaks the build. Can someone check this out please?

**Comment by Rubix982** [comment]
Hey, so I went to the [commit that you gave me](https://github.com/TryGhost/gatsby-starter-ghost/tree/61620ba), and I searched through the tree. The commit you gave me was made on 15th July, and after that only 4 commits have been made, the latest on 21st July. I went through the diffs, and the only files that were effected by the commits were `package.json`, `yarn.lock`, and `plugins/gatsby-plugin-ghost-manifest/yarn.lock`. I'm not sure what changes broke the newest commit, but that's that, if anyone is interested in looking into that. 

Again, thank you so much!

**Comment by Shiiisuiii** [comment]
> 
> 
> @Rubix982 thanks that helps a lot. 😁
> 
> Additionally, I went back to https://github.com/TryGhost/gatsby-starter-ghost/tree/61620ba, a maintenance commit from 2 weeks ago and it works without issue.
> 
> On that page go to Code > Download ZIP. Put the zip in your dir of choice (like your own inited repo). Then go `yarn` and then `gatsby develop`.

thanks man I try to learb Ghost with Gatsby and got the same issue, wait for fix that

**Comment by Shiiisuiii** [comment]
> 
> 
> Hey, so I went to the [commit that you gave me](https://github.com/TryGhost/gatsby-starter-ghost/tree/61620ba), and I searched through the tree. The commit you gave me was made on 15th July, and after that only 4 commits have been made, the latest on 21st July. I went through the diffs, and the only files that were effected by the commits were `package.json`, `yarn.lock`, and `plugins/gatsby-plugin-ghost-manifest/yarn.lock`. I'm not sure what changes broke the newest commit, but that's that, if anyone is interested in looking into that.
> 
> Again, thank you so much!

So after tons of experements I find correct way to solve this problem, if I clone old version of this starter GraphQL problem dissapear but I have a new bug with webpack bundle, the solution is clone this repo as u do before
```
git clone https://github.com/TryGhost/gatsby-starter-ghost.git
cd gatsby-starter-ghost
yarn
```

But before yarn update commands  you need to setup gatsby to latest current version 2.24.11 and after that try to yarn.
At this moment it works fine for me.

**Comment by Shiiisuiii** [comment]
> 
> 
> Hey, so I went to the [commit that you gave me](https://github.com/TryGhost/gatsby-starter-ghost/tree/61620ba), and I searched through the tree. The commit you gave me was made on 15th July, and after that only 4 commits have been made, the latest on 21st July. I went through the diffs, and the only files that were effected by the commits were `package.json`, `yarn.lock`, and `plugins/gatsby-plugin-ghost-manifest/yarn.lock`. I'm not sure what changes broke the newest commit, but that's that, if anyone is interested in looking into that.
> 
> Again, thank you so much!
Of course you need setup its manually because by default we have 2.24.4
https://imgur.com/qhTTwFF
https://imgur.com/IrUU9LF

**Comment by Rubix982** [comment]
Thanks for the testing, @Shiiisuiii !
I just made a pull request #236 to solve this issue.

**Comment by nathanieldavis** [comment]
I am also trying to learn gatsby + ghost and this has been driving me absolutely nuts! Thanks for the fix! @Shiiisuiii @Rubix982 @ogrotten

**Comment by MakanWG** [comment]
Good catch @Rubix982 @Shiiisuiii ! This change was merge as part of https://github.com/TryGhost/gatsby-starter-ghost/commit/56f9bc6158d65183d4b807b404ed9e86ce781a0e It should work properly now with a fresh install.

**Comment by Rubix982** [comment]
Thanks!
I'll try it if the build is working now for me via the original installation wheen I finally get back to work, but it is almost Eid now in Pakistan. Will try this again when I can.

**Comment by Shiiisuiii** [comment]
> 
> 
> Thanks!
> I'll try it if the build is working now for me via the original installation wheen I finally get back to work, but it is almost Eid now in Pakistan. Will try this again when I can.

Need some help in my gulp boilerplate, if you interest please follow my github rebo, I try to publish pullrequest

**Comment by Shiiisuiii** [comment]
> 
> 
> Thanks!
> I'll try it if the build is working now for me via the original installation wheen I finally get back to work, but it is almost Eid now in Pakistan. Will try this again when I can.

Now I'm need some help for my Gulp boilerplate please follow https://github.com/Shiiisuiii/Gulp-Switzerland/issues/2

**Comment by Rubix982** [comment]
It's works smoothly! Thank you for the help, guys. Closing the issue.
