### ISSUE TITLE
RSS feed not sending content-type header

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/gatsby-starter-ghost#24]
RSS feed served via `/rss` is not sending content-type header as xml on production

**Comment by rishabhgrg** [comment]
The `content-type` header in RSS feed requests served on `/rss` is currently set as `text/plain; charset=UTF-8`. While it doesn't affect the feed content and feed is correctly parsed by RSS readers, it needs to be updated to use correct `content-type` value: `text/xml; charset=utf-8`

**Comment by AileenCGN** [comment]
The issue here was with Netlify and not with Gatsby. This also explained, why - even when running in production mode - the `content-type` was always correct locally, but then wrong when it was served from Netlify.

The solution was to add a header rule for the `/rss` route which specifically sets the `content-type` to the correct one.

Fixed with https://github.com/TryGhost/gatsby-starter-ghost/commit/b993dab07579756312e50f9f7a7565fa1175451c
