### ISSUE TITLE
Tags section has duplicate title tags

### ISSUE THREAD

**Issue by javaadpatel** [TryGhost/gatsby-starter-ghost#259]
Hi,
I did an SEO review of my site and it seems that the title property each is the same for each of my tag pages, is it possible to make them unique?

![image](https://user-images.githubusercontent.com/22832462/93300662-821ad200-f7f7-11ea-9456-0259eac87c50.png)

**Comment by aileen** [comment]
Hey @javaadpatel 

I'm not quite sure I understand. Your issue description is very vague. Are you referring to the `<title>` property in `<head>` for tag archive pages?

**Comment by javaadpatel** [comment]
Hi @aileen ,

Yep that's what I mean, the `<title>` property is the same on all these pages, for the blog posts the title property is different but for these pages related to the tag its all the same:
![image](https://user-images.githubusercontent.com/22832462/93423635-b86b5680-f8b6-11ea-91cf-3bb5524696bc.png)

**Comment by javaadpatel** [comment]
Hi @aileen ,

I'd like to try and fix this, where is a good place to start looking?

**Comment by aileen** [comment]
Hey @javaadpatel that's great, as I most probably won't get to this any time soon and it should be fairly straight forward. I The starter has a [meta](https://github.com/TryGhost/gatsby-starter-ghost/tree/master/src/components/common/meta) directory and `tag` archives will use [`WebsiteMeta`](https://github.com/TryGhost/gatsby-starter-ghost/blob/master/src/components/common/meta/WebsiteMeta.js). Probably the easiest would be to generate a custom `title` prop within the tags archive template [here](https://github.com/TryGhost/gatsby-starter-ghost/blob/master/src/templates/tag.js#L20-L24) and pass this title through.

Tags also got a little overhaul recently in Ghost and have now their own `meta_title` and `meta_description`, see [here](https://ghost.org/docs/api/v3/content/#tags). I recommend checking how we grab and process this info for posts (in terms of priority) and then do the same for tags.

Let me know if you need any more info 😃

**Comment by javaadpatel** [comment]
Awesome, thanks for the guidance, will take a look this weekend 👍

**Comment by Giggiux** [comment]
I believe this should be closed, the tag's page already uses the correct name for the title in the following way `{Tag Name} - {Ghost Title}`. This has been changed in 88dce2d

**Comment by aileen** [comment]
Good call, tu!
