### ISSUE TITLE
Ghost page not working with gatsby

### ISSUE THREAD

**Issue by paulh1992** [TryGhost/gatsby-starter-ghost#262]
Hi,

Just got Gatsby working with my local ghost install and this all works fine now with posts.

however i've created a new page in ghost and on Gatsby this just shows me an error (picture attached).

![Screenshot_18](https://user-images.githubusercontent.com/19818643/94424772-ade87100-0182-11eb-87d3-c4f54070497a.png)

It seems like it cant find anything to do with the const page selector? If i comment that line out it then moves onto the page.title line so it seems nothing is coming from the page constant.

on console.log of the const page = data.ghostPage i get this

Warning: Failed prop type: The prop `data.ghostPage` is marked as required in `Page`, but its value is `null`.

Thanks
Paul

**Comment by aileen** [comment]
@paulh1992 I am not able to reproduce this. Just created a page in Ghost and Gatsby is fetching and rendering it fine.

Are you using the latest version of this starter? We just added some improvements last week.

**Comment by btmarouane** [comment]
the error is produced when html field is null please see #281, i think this should not throw an error

**Comment by aileen** [comment]
@btmarouane Thanks for the info! Will have a look at that soon 👀

**Comment by aileen** [comment]
The issue was lying in the gatsby-source-plugin, which didn't allow `html` and other fields to be nullable, even though they  _can_ be nullable within Ghost
