### ISSUE TITLE
We cannnot remove a content which title is data-schema

### ISSUE THREAD

**Issue by yoshi-star** [TryGhost/gatsby-starter-ghost#273]
Hello.
I have a problem and I cannot resolve myself.

In my website, there is a content which title is Data schema.
I would like to remove or to be invisible.

(I cannot find this post on the ghost management console.
 I tried to grep "data-schema" under the project forder ,but I find nothing)

![image](https://user-images.githubusercontent.com/71750189/95834391-d9b94880-0d77-11eb-8871-831c2485a081.png)

How can I resolve it ??

▽html Source code 
```
<a class="post-card" href="/data-schema/">
    <header class="post-card-header">
        <div class="post-card-image"
            style="background-image: url(&quot;https://images.unsplash.com/photo-1532630571098-79a3d222b00d?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjExNzczfQ&amp;s=a88235003c40468403f936719134519d&quot;);">
        </div>
        <div class="post-card-tags"> <span class="">Data schema primary</span></div><span>Featured</span>
        <h2 class="post-card-title">Data schema</h2>
    </header>
    <section class="post-card-excerpt">This is a data schema stub for Gatsby.js and is not used. It must exist for
        builds to function</section>
    <footer class="post-card-footer">
        <div class="post-card-footer-left">
            <div class="post-card-avatar"><img class="author-profile-image"
                    src="https://casper.ghost.org/v2.0.0/images/ghost.png" alt="Data Schema Author"></div><span>Data
                Schema Author</span>
        </div>
        <div class="post-card-footer-right">
            <div>1 min read</div>
        </div>
    </footer>
</a>

```

**Comment by aileen** [comment]
The data schema stubs have been removed around a month ago. Is your version of the starter up to date? And which Ghost instance are you connected to? You should not see this data schema stub as it doesn't exist anymore.

**Comment by yoshi-star** [comment]
Thank you aileen!

Is  the version of starter written in "package.json"?

This in my "package.json" setting.
```
{
  "name": "gatsby-starter-ghost",
  "description": "A starter template to build lightning fast websites with Ghost and Gatsby",
  "version": "1.0.0",
  "license": "MIT",
  "author": "Ghost Foundation",
  "homepage": "https://docs.ghost.org/api/gatsby/",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/tryghost/gatsby-starter-ghost.git"
  },
  "resolutions": {
    "sharp": "0.25.4"
  },
  "engines": {
    "node": ">= 10.13.0"
  },
  "bugs": {
    "url": "https://github.com/tryghost/gatsby-starter-ghost/issues"
  },
  "keywords": [
    "gatsby",
    "ghost"
  ],
  "main": "n/a",
  "scripts": {
    "serve": "gatsby build && NODE_ENV=production gatsby serve",
    "build": "gatsby build",
    "dev": "gatsby develop",
    "lint": "eslint . --ext .js --cache",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "babel-eslint": "10.1.0",
    "eslint": "7.8.1",
    "eslint-plugin-ghost": "1.5.0",
    "eslint-plugin-react": "7.20.6"
  },
  "dependencies": {
    "@tryghost/helpers": "1.1.30",
    "@tryghost/helpers-gatsby": "1.0.34",
    "cheerio": "1.0.0-rc.3",
    "gatsby": "2.24.53",
    "gatsby-awesome-pagination": "0.3.6",
    "gatsby-image": "2.4.16",
    "gatsby-plugin-advanced-sitemap": "1.5.5",
    "gatsby-plugin-catch-links": "2.3.11",
    "gatsby-plugin-feed": "2.5.11",
    "gatsby-plugin-force-trailing-slashes": "1.0.4",
    "gatsby-plugin-google-analytics": "^2.3.13",
    "gatsby-plugin-manifest": "2.4.27",
    "gatsby-plugin-offline": "3.2.26",
    "gatsby-plugin-react-helmet": "3.3.10",
    "gatsby-plugin-sharp": "2.6.31",
    "gatsby-source-filesystem": "2.3.27",
    "gatsby-source-ghost": "4.0.5",
    "gatsby-transformer-sharp": "2.5.14",
    "lodash": "4.17.20",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-helmet": "6.1.0"
  }
}
```

And this is Gatsby version below.
![image](https://user-images.githubusercontent.com/71750189/95928455-5857c980-0dfc-11eb-8d9d-8598d3d6c369.png)

I'm connecting to Ghost Pro Service.

In addition, I would not like to change Design of my site.
Is it possible to update version of my starter without changing design?

I'm a beginner , so I'm sorry for my poor knowledge.

**Comment by yoshi-star** [comment]
These are my source codes below
https://github.com/yoshi-star/forQuestionAboutGatsbyGhostStarter/tree/main/Q

**Comment by aileen** [comment]
Your source code doesn't look like you've followed the install instructions. You'll need to have [a `.ghost.json` file](https://github.com/TryGhost/gatsby-starter-ghost#running) which points to your Ghost instance. It doesn't look like you did many changes yet in your repository, so I'd recommend to make a fresh fork with the correct setup instructions.

If you are a Ghost(Pro) customer, please send a message to support@ghost.org. We'll help you getting this up and running.

I'm closing this issue now, as we only keep issues open for bugs and feature tracking, but not for support requests. If you're self hosting and need assistance, please come over to the [Ghost forum](https://forum.ghost.org/). The chances to solve your problem and get assistance are much bigger than here 😃

**Comment by yoshi-star** [comment]
@aileen 
Thank you !

Im afraid but this problem is caused by gatsby-starter.
(I'm sorry , it's hard to understand.
This source code is just sample. 
I followed the install instructions and I already asked to Ghost Pro Support about this issue.)

I trired to change the URL  from Ghost Pro to empty website at .ghost.json file,
but this content was only in the website like below.
![image](https://user-images.githubusercontent.com/71750189/95934739-9230cc00-0e0c-11eb-913e-fb187a2603d3.png)

We really need to solve this problem.
Could you tell me where can I fix to remove this content in the source code?
(or if you need more information I can send)
I would like to be invisible this one.

Or ,If it's better to update the starter , I will try.

**Comment by aileen** [comment]
> Could you tell me where can I fix to remove this content in the source code?

Like I mentioned above, this information doesn't exist in the source code anymore. It got removed fully a month ago and is also not available in the originally linked Ghost source (https://gatsby.ghost.org/).

> Or ,If it's better to update the starter , I will try.

I highly recommend to update your dependencies. The data-stub improvement was made in the upstream dependency `gatsby-source-ghost` which is now at `4.2.0`. Depending on what you're using (`npm` or `yarn`) run e. g. `yarn upgrade-interactive --exact --latest` for `yarn` or `npm update`

**Comment by yoshi-star** [comment]
@aileen 
Thank you so much!!

I could remove it by update.
Thank you for your advice!
