### ISSUE TITLE
Text "Loading(Static Query)" is at the top of the page

### ISSUE THREAD

**Issue by yoshi-star** [TryGhost/gatsby-starter-ghost#278]
Since I update my dependencies, Text "Loading(Static Query)" is at the top of the page like below.
Could you tell me how can I remove it?

![image](https://user-images.githubusercontent.com/71750189/96096712-179aa600-0f0b-11eb-8ddd-2c21e7d84405.png)

Html code
```
<div style="outline:none" tabindex="-1" id="gatsby-focus-wrapper">
	<div>Loading (StaticQuery)</div>
	
	<div class="viewport">
:
:
```

I tried this but I couldn't resolve
https://github.com/gatsbyjs/gatsby/issues/24890#issuecomment-641841396
(delete node_modules && yarn.lock and "gatsby clean" and regenerating packages doing yarn.
 I also tried same thing by npm)

### Technical details:

* Ghost Version: Ghost Pro Service
* Gatsby Version:2.24.53
* Node Version:v14.10.1
* OS:Amazon Linux 2

**Comment by aileen** [comment]
This seems to be an issue with the upstream dependency, and not the Ghost Gatsby Starter itself. Found another related issue with this [here](https://github.com/gatsbyjs/gatsby/issues/26038). Can you try the steps mentioned there? 

I'm not able to reproduce this. Do you get the same error with a fresh clone of this starter?

**Comment by yoshi-star** [comment]
Thank you !
I read below issue and tried cash delete and down grade but I couln't reslove.
https://github.com/gatsbyjs/gatsby/issues/26038

Anyway, 
I don't get same error  with a fresh clone of this starter ( connect with my Ghost Pro Service).
So I'll try to ask at gatsbyjs issues #26038
Thank you for open issues above.

**Comment by yoshi-star** [comment]
@aileen 

I resolved this problem below.
https://github.com/gatsbyjs/gatsby/issues/26038#issuecomment-709792699

Thank you :)
