### ISSUE TITLE
Cannot find module 'core-js/modules/es6.regexp.to-string'

### ISSUE THREAD

**Issue by BigTony666** [TryGhost/gatsby-starter-ghost#29]
### How problem occurs?

After the starter has been initialized by this:
```sh
gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git
```
And start the development mode:
```sh
npm run dev
```

The Gatsby occurs an error:
```
error Cannot find module 'core-js/modules/es6.regexp.to-string'


  Error: Cannot find module 'core-js/modules/es6.regexp.to-string'

  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15

  - loader.js:507 Function.Module._load
    internal/modules/cjs/loader.js:507:25

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18

  - render-page.js:3 webpackUniversalModuleDefinition
    /Users/bigtony/workplace/BigTony666.github.io/gatsby-starter-ghost/public/render-page.j    s:3:287

  - render-page.js:10 Object.<anonymous>
    /Users/bigtony/workplace/BigTony666.github.io/gatsby-starter-ghost/public/render-page.j    s:10:3

  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30

  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18

  - worker.js:32 Promise
    [gatsby-starter-ghost]/[gatsby]/dist/utils/worker.js:32:35

  - debuggability.js:313 Promise._execute
    [gatsby-starter-ghost]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-starter-ghost]/[bluebird]/js/release/promise.js:483:18
```

### How to fix?

By running:

```sh
npm i core-js --save
```
It will fix the problem.

**Comment by d-cs** [comment]
Did you use yarn or npm to get the dependencies? Wondering how to prevent this from the outset

**Comment by BigTony666** [comment]
@d-cs  Sorry for the late response, I run the `npm i` before I tried `npm run dev`. I just updated the repository and tried again, it seems there is still the same problem.

**Comment by thisishuey** [comment]
I had same issue cloning a Gatsby project to a new machine and only using npm to manage dependencies (I deleted the yarn.lock file from the original project), and taking a stab from @d-cs's yarn vs. npm question above I ran `yarn` and then `npm start` everything appears to be working as expected. I've deleted the yarn.lock file again.

I'm unclear as to which dependency manager we should be using. I assumed it wouldn't matter and that I could pick the one I wanted but it doesn't appear so. Which is less likely to cause issues?

**Comment by AileenCGN** [comment]
> I'm unclear as to which dependency manager we should be using.

The install instructions according to the [README](https://github.com/TryGhost/gatsby-starter-ghost/blob/master/README.md) are correct and are the ones recommended by us:

`yarn` to install the dependencies and
`gatsby develop` to run it it development mode

Alternatively, you can see those scripts in our package.json file, which you can also run (in case you want to type less 😉):

- `yarn dev`
- `yarn build` -> `gatsby build`
- `yarn serve` -> `gatsby build` and then `gatsby serve` which serves the site in production mode

**Comment by Strajk** [comment]
⚠️ If you are experiencing this issue even after installing `core-js`,
be sure to check that you **have version 2**

e.g. `yarn add core-js@^2.6.5`

at least on my env, `core-js@3` did not work

**Comment by heckchuckman** [comment]
@Strajk unfortunately, the latest version of `firebase` breaks with `core-js@^2.6.5`

**Comment by AmaanKulshreshtha** [comment]
Any ideas though, why doesn't it work with core-js@3?

**Comment by Trapintrovert** [comment]
> ### How problem occurs?
> After the starter has been initialized by this:
> 
> ```shell
> gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git
> ```
> 
> And start the development mode:
> 
> ```shell
> npm run dev
> ```
> 
> The Gatsby occurs an error:
> 
> ```
> error Cannot find module 'core-js/modules/es6.regexp.to-string'
> 
> 
>   Error: Cannot find module 'core-js/modules/es6.regexp.to-string'
> 
>   - loader.js:581 Function.Module._resolveFilename
>     internal/modules/cjs/loader.js:581:15
> 
>   - loader.js:507 Function.Module._load
>     internal/modules/cjs/loader.js:507:25
> 
>   - loader.js:637 Module.require
>     internal/modules/cjs/loader.js:637:17
> 
>   - helpers.js:22 require
>     internal/modules/cjs/helpers.js:22:18
> 
>   - render-page.js:3 webpackUniversalModuleDefinition
>     /Users/bigtony/workplace/BigTony666.github.io/gatsby-starter-ghost/public/render-page.j    s:3:287
> 
>   - render-page.js:10 Object.<anonymous>
>     /Users/bigtony/workplace/BigTony666.github.io/gatsby-starter-ghost/public/render-page.j    s:10:3
> 
>   - loader.js:689 Module._compile
>     internal/modules/cjs/loader.js:689:30
> 
>   - loader.js:700 Object.Module._extensions..js
>     internal/modules/cjs/loader.js:700:10
> 
>   - loader.js:599 Module.load
>     internal/modules/cjs/loader.js:599:32
> 
>   - loader.js:538 tryModuleLoad
>     internal/modules/cjs/loader.js:538:12
> 
>   - loader.js:530 Function.Module._load
>     internal/modules/cjs/loader.js:530:3
> 
>   - loader.js:637 Module.require
>     internal/modules/cjs/loader.js:637:17
> 
>   - helpers.js:22 require
>     internal/modules/cjs/helpers.js:22:18
> 
>   - worker.js:32 Promise
>     [gatsby-starter-ghost]/[gatsby]/dist/utils/worker.js:32:35
> 
>   - debuggability.js:313 Promise._execute
>     [gatsby-starter-ghost]/[bluebird]/js/release/debuggability.js:313:9
> 
>   - promise.js:483 Promise._resolveFromExecutor
>     [gatsby-starter-ghost]/[bluebird]/js/release/promise.js:483:18
> ```
> 
> ### How to fix?
> By running:
> 
> ```shell
> npm i core-js --save
> ```
> 
> It will fix the problem.

Thank you. It worked like a charm.

**Comment by shoaib9121** [comment]
>  If you are experiencing this issue even after installing `core-js`,
> be sure to check that you **have version 2**
> 
> e.g. `yarn add core-js@^2.6.5`
> 
> at least on my env, `core-js@3` did not work

downgraded to ^2.6.5
worked perfectly (y)
