### ISSUE TITLE
warn The GraphQL query in the non-page component

### ISSUE THREAD

**Issue by marcoSven** [TryGhost/gatsby-starter-ghost#290]
### Issue Summary

Warning during build

warn The GraphQL query in the non-page component
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments

### To Reproduce

1. gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git
2. yarn
3. yarn serve

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.36.0
* Gatsby CLI version: 2.12.107
* Gatsby Version: 2.24.85
* Node Version: v12.19.0
* OS: mac

**Comment by aileen** [comment]
This is not a bug. It's a warning because it's trying to build `pages` but there are currently none in the CMS. You can either disable the page creation [here](https://github.com/TryGhost/gatsby-starter-ghost/blob/master/gatsby-node.js#L154-L169), or create a page in your CMS to remove this warning.
