### ISSUE TITLE
Can't get the "Deploy to netlify" button to work

### ISSUE THREAD

**Issue by shivangswain** [TryGhost/gatsby-starter-ghost#298]
### Issue Summary

Trying to deploy this on Netlify using the one click "Deploy to netlify" button. Netlify errors out while building.

### To Reproduce

1. I click on the "Deploy to netlify" button on this repo's readme
2. I connect my GitHub, specify my repository, and try to deploy
3. Netlify is not able to finish the build successfully

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Build Logs

> 9:47:31 PM: Build ready to start
> 9:47:33 PM: build-image version: 253f72909528f25a82c4640ca58f2e974d52abd9
> 9:47:33 PM: build-image tag: v3.4.4
> 9:47:33 PM: buildbot version: d7fbddb77714d524c4b4de0312067b122124afee
> 9:47:33 PM: Building without cache
> 9:47:33 PM: Starting to prepare the repo for build
> 9:47:34 PM: No cached dependencies found. Cloning fresh repo
> 9:47:34 PM: git clone https://github.com/TryGhost/gatsby-starter-ghost
> 9:47:35 PM: Preparing Git Reference refs/heads/master
> 9:47:36 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
> 9:47:37 PM: Starting build script
> 9:47:37 PM: Installing dependencies
> 9:47:37 PM: Python version set to 2.7
> 9:47:37 PM: Attempting node version '12' from .nvmrc
> 9:47:38 PM: Downloading and installing node v12.19.0...
> 9:47:38 PM: Downloading https://nodejs.org/dist/v12.19.0/node-v12.19.0-linux-x64.tar.xz...
> 9:47:39 PM: Computing checksum with sha256sum
> 9:47:39 PM: Checksums matched!
> 9:47:41 PM: Now using node v12.19.0 (npm v6.14.8)
> 9:47:41 PM: Started restoring cached build plugins
> 9:47:41 PM: Finished restoring cached build plugins
> 9:47:41 PM: Attempting ruby version 2.7.1, read from environment
> 9:47:42 PM: Using ruby version 2.7.1
> 9:47:43 PM: Using PHP version 5.6
> 9:47:43 PM: 5.2 is already installed.
> 9:47:43 PM: Using Swift version 5.2
> 9:47:43 PM: Started restoring cached node modules
> 9:47:43 PM: Finished restoring cached node modules
> 9:47:43 PM: Started restoring cached yarn cache
> 9:47:43 PM: Finished restoring cached yarn cache
> 9:47:43 PM: Installing yarn at version 1.22.4
> 9:47:43 PM: Installing Yarn!
> 9:47:43 PM: > Downloading tarball...
> 9:47:43 PM: [1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.tOJATU6A3i
> 9:47:43 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> 9:47:43 PM:                                  Dload  Upload   Total   Spent    Left  Speed
> 9:47:43 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 9:47:43 PM: 100    80  100    80    0     0    252      0 --:--:-- --:--:-- --:--:--   253
> 9:47:44 PM: 100    93  100    93    0     0    144      0 --:--:-- --:--:-- --:--:--   144
> 9:47:44 PM: 100   643  100   643    0     0    698      0 --:--:-- --:--:-- --:--:--   698
> 9:47:44 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 9:47:44 PM: 100 1215k  100 1215k    0     0   892k      0  0:00:01  0:00:01 --:--:-- 3198k
> 9:47:44 PM: [2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.tOJATU6A3i.asc
> 9:47:44 PM: 100    84  100    84    0     0   3022      0 --:--:-- --:--:-- --:--:--  3022
> 9:47:44 PM: 100    97  100    97    0     0   1710      0 --:--:-- --:--:-- --:--:--  1710
> 9:47:44 PM: 100   647  100   647    0     0   7254      0 --:--:-- --:--:-- --:--:--  7254
> 9:47:44 PM: 100  1028  100  1028    0     0   8045      0 --:--:-- --:--:-- --:--:--  8045
> 9:47:44 PM: > Verifying integrity...
> 9:47:44 PM: gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
> 9:47:45 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
> 9:47:45 PM: gpg: WARNING: This key is not certified with a trusted signature!
> 9:47:45 PM: gpg:          There is no indication that the signature belongs to the owner.
> 9:47:45 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
> 9:47:45 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
> 9:47:45 PM: > GPG signature looks good
> 9:47:45 PM: > Extracting to ~/.yarn...
> 9:47:45 PM: > Adding to $PATH...
> 9:47:45 PM: > Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.
> 9:47:45 PM: Installing NPM modules using Yarn version 1.22.4
> 9:47:46 PM: yarn install v1.22.4
> 9:47:46 PM: [1/5] Validating package.json...
> 9:47:46 PM: [2/5] Resolving packages...
> 9:47:47 PM: warning Resolution field "sharp@0.26.0" is incompatible with requested version "sharp@^0.25.4"
> 9:47:47 PM: warning Resolution field "sharp@0.26.0" is incompatible with requested version "sharp@^0.25.4"
> 9:47:47 PM: warning Resolution field "sharp@0.26.0" is incompatible with requested version "sharp@^0.25.4"
> 9:47:47 PM: [3/5] Fetching packages...
> 9:47:55 PM: warning url-loader@1.1.2: Invalid bin field for "url-loader".
> 9:48:20 PM: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
> 9:48:20 PM: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
> 9:48:20 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
> 9:48:20 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
> 9:48:20 PM: [4/5] Linking dependencies...
> 9:48:20 PM: warning " > @tryghost/helpers-gatsby@1.0.38" has incorrect peer dependency "react@^16.9.0".
> 9:48:20 PM: warning "@tryghost/helpers-gatsby > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
> 9:48:20 PM: warning "@tryghost/helpers-gatsby > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
> 9:48:20 PM: warning "@tryghost/helpers-gatsby > gatsby-link@2.4.15" has incorrect peer dependency "react@^16.4.2".
> 9:48:20 PM: warning "@tryghost/helpers-gatsby > gatsby-link@2.4.15" has incorrect peer dependency "react-dom@^16.4.2".
> 9:48:20 PM: warning "@tryghost/helpers-gatsby > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
> 9:48:20 PM: warning " > gatsby@2.24.92" has incorrect peer dependency "react@^16.4.2".
> 9:48:20 PM: warning " > gatsby@2.24.92" has incorrect peer dependency "react-dom@^16.4.2".
> 9:48:20 PM: warning "gatsby > gatsby-link@2.4.16" has incorrect peer dependency "react@^16.4.2".
> 9:48:20 PM: warning "gatsby > gatsby-link@2.4.16" has incorrect peer dependency "react-dom@^16.4.2".
> 9:48:20 PM: warning "gatsby > gatsby-react-router-scroll@3.0.15" has incorrect peer dependency "react@^16.4.2".
> 9:48:20 PM: warning "gatsby > gatsby-react-router-scroll@3.0.15" has incorrect peer dependency "react-dom@^16.4.2".
> 9:48:20 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
> 9:48:20 PM: warning " > gatsby-awesome-pagination@0.3.6" has incorrect peer dependency "react@^16.0.0".
> 9:48:20 PM: warning "react-helmet > react-side-effect@2.1.0" has incorrect peer dependency "react@^16.3.0".
> 9:48:40 PM: [5/5] Building fresh packages...
> 9:48:49 PM: Done in 62.68s.
> 9:48:49 PM: NPM modules installed using Yarn
> 9:48:49 PM: Started restoring cached go cache
> 9:48:49 PM: Finished restoring cached go cache
> 9:48:49 PM: go version go1.14.4 linux/amd64
> 9:48:49 PM: go version go1.14.4 linux/amd64
> 9:48:49 PM: Installing missing commands
> 9:48:49 PM: Verify run directory
> 9:48:50 PM: ​
> 9:48:50 PM: ┌─────────────────────────────┐
> 9:48:50 PM: │        Netlify Build        │
> 9:48:50 PM: └─────────────────────────────┘
> 9:48:50 PM: ​
> 9:48:50 PM: ❯ Version
> 9:48:50 PM:   @netlify/build 5.2.1
> 9:48:50 PM: ​
> 9:48:50 PM: ❯ Flags
> 9:48:50 PM:   deployId: 5fa5771b9aff8a0ebf2cb2ce
> 9:48:50 PM:   mode: buildbot
> 9:48:50 PM: ​
> 9:48:50 PM: ❯ Current directory
> 9:48:50 PM:   /opt/build/repo
> 9:48:50 PM: ​
> 9:48:50 PM: ❯ Config file
> 9:48:50 PM:   /opt/build/repo/netlify.toml
> 9:48:50 PM: ​
> 9:48:50 PM: ❯ Context
> 9:48:50 PM:   production
> 9:48:50 PM: ​
> 9:48:50 PM: ┌────────────────────────────────────┐
> 9:48:50 PM: │ 1. build.command from netlify.toml │
> 9:48:50 PM: └────────────────────────────────────┘
> 9:48:50 PM: ​
> 9:48:50 PM: $ NODE_ENV=production gatsby build
> 9:48:54 PM: error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.
> 9:48:54 PM: 
> 9:48:54 PM:   Error: siteUrl can't be localhost and needs to be configured in siteConfig. Ch  eck the README.  
> 9:48:54 PM:   - gatsby-config.js:26 Object.<anonymous>
> 9:48:54 PM:     /opt/build/repo/gatsby-config.js:26:11
> 9:48:54 PM:   
> 9:48:54 PM:   - v8-compile-cache.js:178 Module._compile
> 9:48:54 PM:     [repo]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30
> 9:48:54 PM:   
> 9:48:54 PM:   - loader.js:1035 Object.Module._extensions..js
> 9:48:54 PM:     internal/modules/cjs/loader.js:1035:10
> 9:48:54 PM:   
> 9:48:54 PM:   - loader.js:879 Module.load
> 9:48:54 PM:     internal/modules/cjs/loader.js:879:32
> 9:48:54 PM:   
> 9:48:54 PM:   - loader.js:724 Function.Module._load
> 9:48:54 PM:     internal/modules/cjs/loader.js:724:14
> 9:48:54 PM:   
> 9:48:54 PM:   - loader.js:903 Module.require
> 9:48:54 PM:     internal/modules/cjs/loader.js:903:19
> 9:48:54 PM:   
> 9:48:54 PM:   - v8-compile-cache.js:159 require
> 9:48:54 PM:     [repo]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
> 9:48:54 PM:   
> 9:48:54 PM:   - get-config-file.ts:30 getConfigFile
> 9:48:54 PM:     [repo]/[gatsby]/src/bootstrap/get-config-file.ts:30:20
> 9:48:54 PM:   
> 9:48:54 PM:   - initialize.ts:113 initialize
> 9:48:54 PM:     [repo]/[gatsby]/src/services/initialize.ts:113:50
> 9:48:54 PM:   
> 9:48:54 PM:   - index.ts:42 bootstrap
> 9:48:54 PM:     [repo]/[gatsby]/src/bootstrap/index.ts:42:15
> 9:48:54 PM:   
> 9:48:54 PM:   - build.ts:93 build
> 9:48:54 PM:     [repo]/[gatsby]/src/commands/build.ts:93:47
> 9:48:54 PM:   
> 9:48:54 PM: 
> 9:48:54 PM: not finished open and validate gatsby-configs - 0.164s
> 9:48:54 PM: ​
> 9:48:54 PM: ┌─────────────────────────────┐
> 9:48:54 PM: │   "build.command" failed    │
> 9:48:54 PM: └─────────────────────────────┘
> 9:48:54 PM: ​
> 9:48:54 PM:   Error message
> 9:48:54 PM:   Command failed with exit code 1: NODE_ENV=production gatsby build
> 9:48:54 PM: ​
> 9:48:54 PM:   Error location
> 9:48:54 PM:   In build.command from netlify.toml:
> 9:48:54 PM:   NODE_ENV=production gatsby build
> 9:48:54 PM: ​
> 9:48:54 PM:   Resolved config
> 9:48:54 PM:   build:
> 9:48:54 PM:     command: NODE_ENV=production gatsby build
> 9:48:54 PM:     commandOrigin: config
> 9:48:54 PM:     publish: /opt/build/repo/public
> 9:48:54 PM: Caching artifacts
> 9:48:54 PM: Started saving node modules
> 9:48:54 PM: Finished saving node modules
> 9:48:54 PM: Started saving build plugins
> 9:48:54 PM: Finished saving build plugins
> 9:48:54 PM: Started saving yarn cache
> 9:48:54 PM: Finished saving yarn cache
> 9:48:54 PM: Started saving pip cache
> 9:48:54 PM: Finished saving pip cache
> 9:48:54 PM: Started saving emacs cask dependencies
> 9:48:54 PM: Finished saving emacs cask dependencies
> 9:48:54 PM: Started saving maven dependencies
> 9:48:54 PM: Finished saving maven dependencies
> 9:48:54 PM: Started saving boot dependencies
> 9:48:54 PM: Finished saving boot dependencies
> 9:48:54 PM: Started saving go dependencies
> 9:48:54 PM: Finished saving go dependencies
> 9:48:58 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
> 9:48:58 PM: Failing build: Failed to build site
> 9:48:58 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
> 9:48:59 PM: Finished processing build request in 1m25.828442725s

### Technical details:

* Ghost Version: 3.x
* Gatsby Version: 2.24.92
* Node Version: 12.19.0
* OS: Ubuntu 16.04 (Netlify)

**Comment by shivangswain** [comment]
I ended up pulling this repo to my own one (because it was empty) and then changing the siteURL to the one on Netlify. This resulted in a successful but how was I supposed to know this? I think thus the ReadMe can be updated to reflect having to clone this repo, adding the siteURL and then being able to successfully deploy the site.

**Comment by aileen** [comment]
Hey @shivangswain

The error is fully intentional to avoid sites being pushed to production without updating the `siteUrl` first, as otherwise every deploy uses a ghost.org URL as canonical which is not desired. 

The Readme states exactly that:

> Finally, configure your desired URL in siteConfig.js, so links (e. g. canonical links) are generated correctly. You can also update other default values, such as postsPerPage in this file.
