### ISSUE TITLE
How to add tag conditions in gatsby ghost blog?

### ISSUE THREAD

**Issue by fed2310** [TryGhost/gatsby-starter-ghost#310]
How to add conditions like 
```
{{#has slug="welcome" tag="getting started"}}
  ...Will execute if the slug is welcome OR the tag is getting-started...
{{/has}}
```

and also something like this
```
{{#get "posts" limit="3" include="tags" filter="tag:top-posts"}}
{{#if posts}}
{{#foreach posts}} 
	..... Top Post Card						    
{{/foreach}}
{{/if}}
{{/get}}
```

Any help will be highly appreciated.

**Comment by aileen** [comment]
Hey @fed2310   👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://ghost.org/docs/) or the official [Gatsby docs](https://www.gatsbyjs.com/docs/). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
