### ISSUE TITLE
Missing image referenced in siteConfig.js

### ISSUE THREAD

**Issue by d-cs** [TryGhost/gatsby-starter-ghost#32]
A minor issue. In:

https://github.com/TryGhost/gatsby-starter-ghost/blob/b993dab07579756312e50f9f7a7565fa1175451c/src/utils/siteConfig.js#L9

The corresponding image doesn't exist in:

https://github.com/TryGhost/gatsby-starter-ghost/blob/master/src/images

The effect will be 404 on site share of the demo on social media. I do find having all the files there useful to know what I need to create to customise though. Happy to fix & PR if you supply the image.

**Comment by AileenCGN** [comment]
@d-cs Thanks for letting us know! I'll look into providing a better (aka existing) image to have the default setup working out of the box 👍
