### ISSUE TITLE
When we will get an update version of Ghost 4?

### ISSUE THREAD

**Issue by 007AMAN007** [TryGhost/gatsby-starter-ghost#355]
Hi,

When we will get an update version of Ghost 4, any estimate date ?

**Comment by aileen** [comment]
Hi @007AMAN007 

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.
