### ISSUE TITLE
Translate all the helper with gatsby

### ISSUE THREAD

**Issue by MaralS** [TryGhost/gatsby-starter-ghost#39]
Hi 
I was wondering how to translate the helpers such as the reading time or other string for my gatsby website.
I'm using the gatsby starter ghost boilerplate.
Thanks

**Comment by AileenCGN** [comment]
I already answered your question in out forum [here](https://forum.ghost.org/t/translation-of-the-helpers-with-gatsby/6187/2). Please don't crosspost 😊 

The tl;dr: it's not supported, contributions (incl. proper spec) are always welcome!
