### ISSUE TITLE
Broken install

### ISSUE THREAD

**Issue by maikeldotuk** [TryGhost/gatsby-starter-ghost#390]
Welcome to the Gatsby Starter Ghost GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

For questions related to the usage of Gatsby or GraphQL, please check out their docs at https://www.gatsbyjs.org/ and https://graphql.org/

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Gatsby.js itself, please report it at the Gatsby repo ➡️ https://github.com/gatsbyjs/gatsby/issues/new.

### Issue Summary

When I install it as described I get an error. 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-ghost@2.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from @tryghost/helpers-gatsby@1.0.51
npm ERR! node_modules/@tryghost/helpers-gatsby
npm ERR!   @tryghost/helpers-gatsby@"1.0.51" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/maikel/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maikel/.npm/_logs/2021-06-18T13_11_38_060Z-debug.log

### To Reproduce

gatsby new my-gatsby-site https://github.com/TryGhost/gatsby-starter-ghost.git

It doesn't happen if I clone the project and instead use yarn. 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Node Version: v16.1.0
* NPM version 7.11.2
* OS: Windows 10 (Ubuntu 20 in WSL).

**Comment by aileen** [comment]
Thanks for reporting! Can reproduce as well

**Comment by ManiMuridi** [comment]
Hello, I just tried to install this and got that same exact error. Is there a workaround for this? I really would like to setup my Ghost blog using gatsby.

**Comment by OliverHuntsman** [comment]
I also installed this then npm did not work, ran yarn and it seemed to work but I get a fault when I 

`warn [gatsby-transformer-sharp] The "fixed" and "fluid" resolvers are now deprecated. Switch to "gatsby-plugin-image" for better performance and
a simpler API. See https://gatsby.dev/migrate-images to learn how.
success run static queries - 0.107s - 5/5 46.88/s
success run page queries - 0.094s - 3/3 31.83/s

 ERROR 

Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
 - options should be one of these:
   object { resourceRegExp, contextRegExp? } | object { checkResource }
   Details:
    * options misses the property 'resourceRegExp'. Should be:
      RegExp
      -> A RegExp to test the request against.
    * options misses the property 'checkResource'. Should be:
      function
      -> A filter function for resource and context.



  ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
   - options should be one of these:
     object { resourceRegExp, contextRegExp? } | object { checkResource }
     Details:
      * options misses the property 'resourceRegExp'. Should be:
        RegExp
        -> A RegExp to test the request against.
      * options misses the property 'checkResource'. Should be:
        function
        -> A filter function for resource and context.
  
  - validate.js:105 validate
    [gatsby-starter-ghost]/[schema-utils]/dist/validate.js:105:11
  
  - create-schema-validation.js:16 
    [gatsby-starter-ghost]/[webpack]/lib/util/create-schema-validation.js:16:17
  
  - IgnorePlugin.js:28 new IgnorePlugin
    [gatsby-starter-ghost]/[webpack]/lib/IgnorePlugin.js:28:3
  
  - webpack-plugins.ts:16 Object.ignore
    [gatsby-starter-ghost]/[gatsby]/src/utils/webpack-plugins.ts:16:12
  
  - webpack-utils.ts:767 Object.moment
    [gatsby-starter-ghost]/[gatsby]/src/utils/webpack-utils.ts:767:13
  
  - webpack.config.js:211 getPlugins
    [gatsby-starter-ghost]/[gatsby]/src/utils/webpack.config.js:211:15
  
  - webpack.config.js:512 module.exports
    [gatsby-starter-ghost]/[gatsby]/src/utils/webpack.config.js:512:14
  
  - build-html.ts:180 buildRenderer
    [gatsby-starter-ghost]/[gatsby]/src/commands/build-html.ts:180:18
  
  - start-server.ts:118 createIndexHtml
    [gatsby-starter-ghost]/[gatsby]/src/utils/start-server.ts:118:32
  
  - start-server.ts:156 startServer
    [gatsby-starter-ghost]/[gatsby]/src/utils/start-server.ts:156:5
  
  - start-webpack-server.ts:44 startWebpackServer
    [gatsby-starter-ghost]/[gatsby]/src/services/start-webpack-server.ts:44:7
  

not finished Building development bundle - 0.208s
`

` System:
    OS: macOS 11.5.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.1.2
  npmPackages:
    gatsby: 3.12.1 => 3.12.1
    gatsby-awesome-pagination: 0.3.8 => 0.3.8
    gatsby-image: 3.11.0 => 3.11.0
    gatsby-plugin-advanced-sitemap: 2.0.0 => 2.0.0
    gatsby-plugin-catch-links: 3.12.0 => 3.12.0
    gatsby-plugin-feed: 3.12.0 => 3.12.0
    gatsby-plugin-force-trailing-slashes: 1.0.5 => 1.0.5
    gatsby-plugin-manifest: 3.12.0 => 3.12.0
    gatsby-plugin-offline: 4.12.0 => 4.12.0
    gatsby-plugin-react-helmet: 4.12.0 => 4.12.0
    gatsby-plugin-sharp: 3.12.0 => 3.12.0
    gatsby-source-filesystem: 3.12.0 => 3.12.0
    gatsby-source-ghost: 4.2.4 => 4.2.4
    gatsby-transformer-sharp: 3.12.0 => 3.12.0
  npmGlobalPackages:
    gatsby-cli: 4.2.0
    gatsby-starter-netlify-cms: 1.1.3


`

**Comment by johnwess** [comment]
I am getting the same error as well. 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-ghost@2.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from @tryghost/helpers-gatsby@1.0.61
npm ERR! node_modules/@tryghost/helpers-gatsby
npm ERR!   @tryghost/helpers-gatsby@"1.0.61" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\johnd\AppData\Local\npm-cache\eresolve-report.txt for a full report.`

**Comment by Queenscripts** [comment]
I am also receive a similar error upon running ``` gatsby develop ```  ERROR 

Invalid options object. Ignore Plugin has been initialized using an options object that does not match the
API schema.
 - options should be one of these:
   object { resourceRegExp, contextRegExp? } | object { checkResource }
   Details:
    * options misses the property 'resourceRegExp'. Should be:
      RegExp
      -> A RegExp to test the request against.
    * options misses the property 'checkResource'. Should be:
      function
      -> A filter function for resource and context.



  ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that do
  es not match the API schema.
   - options should be one of these:
     object { resourceRegExp, contextRegExp? } | object { checkResource }
     Details:
      * options misses the property 'resourceRegExp'. Should be:
        RegExp
        -> A RegExp to test the request against.
      * options misses the property 'checkResource'. Should be:
        function
        -> A filter function for resource and context.

**Comment by 3ux1n3** [comment]
have same issue anyone found solution ?

**Comment by aileen** [comment]
Should be fixed with #510
