### ISSUE TITLE
Adding markdown pages and posts outside of Ghost

### ISSUE THREAD

**Issue by max-l** [TryGhost/gatsby-starter-ghost#40]
I want to create a Gatsby static front end that displays posts from two sources:

1. a Ghost instance
2. pages written in Markdown 

This project is a great starter for feeding from Ghost, just tried it and it works great, 
I know there are examples on how to create markdown sites with Gatsby, but I 
suppose markdown posts will need to have the same metadata as posts coming from 
Ghost. I assume some Graphql query will concatenate a list of posts coming from the two sources, etc.

The idea is to accomodate 2 types of users: developers that prefer markdown and non devs that prefer the Ghost editor.

**Comment by AileenCGN** [comment]
You can see a very highly customised usage of Ghost resources in combination with Markdown pages in our Ghost Docs:

https://docs.ghost.org

The repository is here: https://github.com/TryGhost/docs

Hope that helps!

**Comment by max-l** [comment]
@AileenCGN  I'm not finding the docs you are refering to, can you point to a specific page in the doc ? 

I realize there are two ways to mix mardown content and ghost edited pages, 
1. write markdown pages within Ghost
2. write markdown pages within the gatsby front end. 

I suppose you are refering (the docs I cannot find) to ways to write markdown pages that end up in Ghosts database ?  
I would actually prefer option 2, that would allow me to have the markdown pages in source control

**Comment by AileenCGN** [comment]
I was not pointing you to a documentation on how to solve what you want to solve. I was pointing you towards the Ghost Docs, and the open source repository, where you can see exactly how it _can_ be done. Most importantly, check out the `createPages` API 👉 https://github.com/TryGhost/docs/blob/master/gatsby/createPages.js

If you're looking on further information on how to use Gatsby, then their documentation is the right place for you to look 👉 https://www.gatsbyjs.org/docs/
