### ISSUE TITLE
The article page has no release date, how can I add this?

### ISSUE THREAD

**Issue by heshanfu** [TryGhost/gatsby-starter-ghost#41]
This project is very cool, but the article page has no release date. How can I add this?

**Comment by AileenCGN** [comment]
Hey @heshanfu 

You would need to adjust the `post.js` template file to include the `published_at_pretty` and `published_at` fields and then use them within your jsx:

```jsx
<time dateTime={post.published_at}>{post.published_at_pretty}</time>
```

You can see all available fields for a post [here](https://github.com/TryGhost/gatsby-starter-ghost/blob/8b2faec9a95ebb762f6cf029226558c8b80be7bf/src/utils/fragments.js#L56-L57).
