### ISSUE TITLE
Galleries don't render correctly - images are elongated vertically

### ISSUE THREAD

**Issue by hooshd** [TryGhost/gatsby-starter-ghost#43]
Hi,

Galleries don't render correctly in this starter.

Here's the page in production: https://hooshmand.net/galleries-test/
Here's the test page, published on Gatsby/Netlify: https://beta.hooshmand.net/galleries-test/

I've previously encountered this issue with other handlebars templates before, but I didn't diagnose the issue (or I'd fix it myself)!

If you can point me at documentation I'd be happy to try to fix it.

**Comment by AileenCGN** [comment]
The Gatsby starter is more a basic starting point from where you can do your own styles. The CSS that comes with it is down to a minimum just so you have all the freedom to do whatever you feel like it.

A good starting point on how to style the gallery can be found in the Ghost Casper theme [here](https://github.com/TryGhost/Casper/blob/master/assets/css/screen.css#L1904-L1937) or in the Ghost Starter theme [here](https://github.com/TryGhost/Starter/blob/master/assets/css/components/ghost.css#L62-L99)

**Comment by JohnONolan** [comment]
This is a gatsby starter, not a theme, so it's intended to be a barebones scaffolding to kickstart development :)

**Comment by hooshd** [comment]
I will go berserk on it and try to make it way better!

Also thanks for being so patient. @JohnONolan I honestly love your work and ethos, and @AileenCGN you're incredibly helpful here and on the forum. I appreciate both of you.
