### ISSUE TITLE
Editing Ghost Post HTML

### ISSUE THREAD

**Issue by kennandavison** [TryGhost/gatsby-starter-ghost#46]
Hi - does anyone know how I'd go about editing the generated Ghost Post HTML? I want to add custom css classes without doing custom html for each post.

**Comment by AileenCGN** [comment]
Hey!

I don't think you're able to do that, unless you manipulate then in a clone of [the source plugin](https://github.com/TryGhost/gatsby-source-ghost) for Ghost.
