### ISSUE TITLE
Starter development roadmap

### ISSUE THREAD

**Issue by acollien** [TryGhost/gatsby-starter-ghost#47]
Hi Team - still very new to JAMstack, so understanding of development and integrations is quite basic.

Got your starter template working, but was expecting something closer to the user experience of the actual Casper theme.

Is there plans to develop his starter?

For example, I came across [this project](https://github.com/scttcper/gatsby-casper), and it seems to be a bit more in-line with the feel of the full casper theme (though it doesn't integrate with ghost - yet (?)). [demo here](https://gatsby-casper.netlify.com/)

**Comment by AileenCGN** [comment]
A Gatsby starter is not a theme, but a starter, so it's intended to be a barebones scaffolding to kickstart development.

The project you're referring to has the intention of looking like Ghost's default theme Casper. This is not the intention we have with this starter.

In this beautiful open source world, you could take this starter to get your Gatsby + Ghost setup up and running and then "marry" it with the project you're referring to in terms of styles and components.

I hope that helps! 😊 

Please share your thoughts and progress (or ask further questions) over in our forum [here](https://forum.ghost.org) where you'll get much better support than here 😉
