### ISSUE TITLE
Excerpt is null in API

### ISSUE THREAD

**Issue by yoonwaiyan** [TryGhost/gatsby-starter-ghost#53]
### Issue Summary
Hi, is `excerpt` a new field in newest version of Ghost? I've seen a pull request in #11 that changed from `custom_excerpt` to `excerpt` but I have problem accessing `excerpt` on my side. It returns `null` from my API.

### To Reproduce

1. Changed `.ghost.json` to my Ghost blog and add credentials.
2. Run `$ gatsby develop`

### Technical details:

* Ghost Version: 2.9.1
* Gatsby Version: 2.3.34
* Node Version: v10.5.0
* OS: macOS 10.13.6

**Comment by AileenCGN** [comment]
Hey @yoonwaiyan 

I updated the README to state the minimum required Ghost version that is needed to work flawlessly with this starter. Please update your Ghost installation to latest. This should resolve your issues.

Please use our [forum](https://forum.ghost.org) for questions, as we only keep GitHub issues open for bugs.
