### ISSUE TITLE
Need to merge gatsby-starter-ghost starter with gatsby-serif-theme starter. How do I achieve this?

### ISSUE THREAD

**Issue by jnsrikanth** [TryGhost/gatsby-starter-ghost#59]
I am trying to merge the gatsby-starter-ghost with gatsby-serif-theme. However, with two separate gatsby-config.js and differing project/folder/file structures, I am finding it very difficult to get a breakthrough in going about merging these two templates. 

Please note that I want gatsby-starter-ghost starter to be a sub-folder or a page within the src folder of my gatsby-serif-theme main site. My key challenge is to decode two separate gatsby-config.js files (from the two themes) before merging them together and several other assets/files into the main site (in this gatsby-serif-theme).

How do I go about this? Let me know.

--------------^ Click "Preview" for a nicer view!

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫.

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Forum](https://forum.ghost.org/c/help)
- [Gatsby API reference](https://docs.ghost.org/api/gatsby/)
- [Content API Docs](https://docs.ghost.org/api/content/)
- [Gatsby.js](https://www.gatsbyjs.org)
- [GraphQL](https://graphql.org/)
- [Feature Requests / Ideas](https://forum.ghost.org/c/Ideas)
- [Contributing Guide](https://docs.ghost.org/docs/contributing)
- [Self-hoster Docs](https://docs.ghost.org/)

**Comment by AileenCGN** [comment]
Hey @jnsrikanth   👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

> Please note that I want gatsby-starter-ghost starter to be a sub-folder or a page within the src folder of my gatsby-serif-theme main site.

This is an absolute Gatsby-only request and your much better off seeking help in their community. But I honestly doubt very much that this is possible, as Gatsby requires their files to be present on the root level. You can still merge the configs and add a prefix for everything that comes from Ghost on e. g. `/blog`.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
