### ISSUE TITLE
TypeError: Cannot read property 'concat' of null

### ISSUE THREAD

**Issue by mskian** [TryGhost/gatsby-starter-ghost#62]
```js
error Plugin gatsby-source-ghost returned an error


  TypeError: Cannot read property 'concat' of null
  
  - gatsby-node.js:102 api.settings.browse.then
    [my-gatsby-sitet]/[gatsby-source-ghost]/gatsby-node.js:102:53
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

Plugin Version : Latest (3.4.1)

**Comment by gargol** [comment]
Hi @mskian :wave: Can you please add a bit more details on under what circumstances/environment this error happens? What are the exact steps to reproduce it?

**Comment by mskian** [comment]
Just Update the recent Changes done by @AileenCGN 

This error Shown while Building the Gatsby site

**Comment by gargol** [comment]
Am I understanding it correctly, it happens when you run the initialization command `gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git`?

**Comment by mskian** [comment]
```bash
gatsby build
```

This issue caused after upgrading the Gatsby-source-ghost plugin no issue on previous versions

**Comment by AileenCGN** [comment]
Yeah, sorry about that! Introduced with the lasted update. Fix coming right meow!!!
