### ISSUE TITLE
The Netlify can't connect the 127.0.0.1:2368

### ISSUE THREAD

**Issue by jiangskye** [TryGhost/gatsby-starter-ghost#65]
When I put the project to the Netlify and change connect API, Url to my localhost. The Netlify can't connect the 127.0.0.1:2368.

**Comment by AileenCGN** [comment]
Hey @jiangskye  👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) or external sites, such as Netlify or Gatsby for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

This is not an issue with this starter. Please check out the docs for the [Netlify CLI](https://www.netlify.com/docs/cli/) (if you're using this) and read the section about using your own env variables in our [README](https://github.com/TryGhost/gatsby-starter-ghost#deploying-with-netlify)
