### ISSUE TITLE
Magic path to someone's file

### ISSUE THREAD

**Issue by ptalmeida** [TryGhost/gatsby-starter-ghost#71]
This doesn't look good: 

https://github.com/TryGhost/gatsby-starter-ghost/blob/a6469e16e1340d0965fce921be8b6ad81d1ae556/plugins/gatsby-plugin-ghost-manifest/gatsby-ssr.js#L11

Not versed in Gatsby so I won't open a PR right now.

**Comment by AileenCGN** [comment]
Cheers!!! I updated the plugins and the file (which was still like this from the first development process) is now fixed 😉
