### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by gursewaksingh-jaw** [TryGhost/gatsby-starter-ghost#73]
> pngquant-bin@5.0.1 postinstall E:\Development\Git\someapp\node_modules\pngquant-bin
> node lib/install.js

  ‼ Response code 503 (Backend unavailable, connection timeout)
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (E:\Development\Git\someapp\node_modules\execa\index.js:231:11)

**Comment by daviddarnes** [comment]
Hey @gursewaksingh-jaw, may I ask what your setup is? Guessing from the error log that you're on a Windows machine, check out the official Gatsby docs regarding the installation process for Windows machines https://www.gatsbyjs.org/docs/gatsby-on-windows/
