### ISSUE TITLE
Running "gatsby build" throws a GLib error?

### ISSUE THREAD

**Issue by JaneJeon** [TryGhost/gatsby-starter-ghost#74]
Hi, I just cloned this repo, installed dependencies, _didn't touch_ the `.ghost.json` file, and just ran `gatsby build`.

It ran fine until the "Building static HTML for pages" step, and then sharp throws an error for some reason that I can't see (I've tried `yarn serve` as well):

```
(sharp:50470): GLib-CRITICAL **: 23:13:37.186: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

And here's the screenshot: https://i.imgur.com/XKKmcSK.png.

For reference, I'm using `node v12.8.0`, `yarn 1.17.3`, and `ghost 2.21.0` running on heroku using [this template](https://github.com/SNathJr/ghost-on-heroku).

I don't know what could be causing this... given the `sharp` error, I'm guessing the problem's on the static site generation end (instead of the headless CMS end).

**Comment by daviddarnes** [comment]
Hi @JaneJeon! Have you tried setting a newer version of yarn in your configuration? https://github.com/gatsbyjs/gatsby/issues/3570#issuecomment-366569151

FYI The configuration you linked to is for the Ghost CMS itself and not designed for Gatsby applications
