### ISSUE TITLE
Publication cover does not get pulled through to resultant gatsby site

### ISSUE THREAD

**Issue by mannp** [TryGhost/gatsby-starter-ghost#75]
### Issue Summary

Publication cover does not get pulled through to resultant gatsby site.

### To Reproduce

1. Set a Publication cover in Ghost admin
2. Confirm the Publication cover is displayed on the Ghost version of the site, confirming an acceptable image

My expectation would be that this Publication cover would be pulled through to the gatsby site?

### Technical details:

* Ghost Version:
    Version 2.27.0
    Environment production
    Database mysql
    Mail SMTP
* Gatsby Version:
Gatsby CLI version: 2.7.7
Gatsby version: 2.13.45
* Node Version:
v11.15.0
* OS:
Arch Linux

**Comment by daviddarnes** [comment]
Thanks @mannp! I've added it in, for reference the publication cover can be got the settings API endpoint under `cover_image`: https://ghost.org/docs/api/v2/content/#settings

**Comment by mannp** [comment]
Thanks @daviddarnes confirmed working here now :)
