### ISSUE TITLE
gatsby develop fails to build gatsby-starter-ghost

### ISSUE THREAD

**Issue by kylenovak** [TryGhost/gatsby-starter-ghost#79]
### Issue Summary

gatsby-starter-ghost doesn't build; ie. "gatsby develop" fails for the gatsby-starter-ghost project.

### To Reproduce

1. gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git
2. yarn
3. gatsby develop

### Error Output
![gatsby_error](https://user-images.githubusercontent.com/7276427/64502454-d0fc6600-d28b-11e9-8963-904e85ae2317.png)

I have tried the recommendations in the above image, but I get the same error.
 
### Technical details:

* Ghost Version: 1.11.0
* Gatsby Version: 2.14.0
* Gatsby CLI Version: 2.7.44
* Node Version: 10.16.3
* OS: Windows 10

**Comment by kylenovak** [comment]
Was able to figure it out after multiple issues. Sharp, gatsby-source-contentful were the main culprits... Not a true solution, as some of the dependencies just are broken and don't work well with each other, so had to rollback gatsby and gatsby-source-contentful to older releases/versions.  Use fixed versioning (ie. remove the carets^) like below and this should at least work.

`"devDependencies": {
    "eslint": "6.2.2",
    "eslint-plugin-ghost": "0.5.0",
    "eslint-plugin-react": "7.14.3"
  },
  "dependencies": {
    "@tryghost/helpers": "1.1.8",
    "@tryghost/helpers-gatsby": "1.0.11",
    "cheerio": "1.0.0-rc.3",
    "gatsby": "2.9.10",
    "gatsby-awesome-pagination": "0.3.4",
    "gatsby-image": "2.2.14",
    "gatsby-plugin-advanced-sitemap": "1.4.1",
    "gatsby-plugin-catch-links": "2.1.5",
    "gatsby-plugin-feed": "2.3.7",
    "gatsby-plugin-force-trailing-slashes": "1.0.4",
    "gatsby-plugin-manifest": "2.2.15",
    "gatsby-plugin-offline": "2.2.10",
    "gatsby-plugin-react-helmet": "3.1.5",
    "gatsby-plugin-sharp": "2.2.20",
    "gatsby-remark-images-contentful": "2.1.11",
    "gatsby-source-contentful": "2.0.41",
    "gatsby-source-filesystem": "2.1.18",
    "gatsby-source-ghost": "3.4.5",
    "gatsby-transformer-sharp": "2.2.13",
    "gatsby-transformer-sqip": "2.1.23",
    "lodash": "4.17.15",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-helmet": "5.2.1",
    "sharp": "0.23.0"
  }`

**Comment by Linkmetal** [comment]
Having the same issue on a clean install of the example, I also tried the workaround of @kylenovak and didn't work.

**Comment by AileenCGN** [comment]
This still seems to be a big issue upstream. Updating the dependencies here is a bit of a pain too.

A couple of things you can try:

- delete your `yarn.lock` or `package-lock.json` file
- delete your node modules: `rm -rf node_modules`
- run `yarn --force` or `npm rebuild && npm install`

I also followed for now this advice [here](https://github.com/gatsbyjs/gatsby/issues/16957) (I'm keeping a close eye on this issue), which seems to help, so best you either update your starter again, or just pull the last commits into your version.

Hope that helps!!
