### ISSUE TITLE
Assets from cdn in a blog post are not loading after original load

### ISSUE THREAD

**Issue by cotyhamilton** [TryGhost/gatsby-starter-ghost#83]
### Issue Summary

I'm loading react in a blog post to add a react component to a single blog post. On the first load everything is fine or while using an incognito browser, but on subsequent loads I receive these errors

```
The FetchEvent for "https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors
```

```
The FetchEvent for "https://unpkg.com/react@16/umd/react.production.min.js" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors
```

Safari, Firefox, and chrome on mac and windows

### To Reproduce

1. Create a blog bost
2. Add the following to the blog post in an html block
```
<div id="react-code-block-container" style="width: 100%"></div>
<script src="https://unpkg.com/react@16/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" crossorigin></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.js" crossorigin></script>
<script type="text/babel">
    'use strict';

    const data = {
      color: 'red',
      wheels: 4,
      engine: {
        cylinders: 4,
        size: 2.2
      }
    }
    
    const style = { background: "#001f3f" }

    const codeBlock = (
      <pre style={style}>
      	<code>
        	{JSON.stringify(data, null, 2)}
    	</code>
      </pre>
    );

	ReactDOM.render(codeBlock, document.getElementById('react-code-block-container'));
</script>
```

Again, first load the component is there, all resources downloaded. On subsequent loads the resources are not loaded.

### Technical details:

* Ghost Version: docker image
* Gatsby Version: 2.14.0

The netlify builds and serves the site from their cdn

The blog post https://www.cotyhamilton.com/how-to-pretty-print-json-in-html-with-javascript/

The scripts don't show up at all in the network requests when running gatsby locally with the dev server. My ghost installation shows the post correctly though.

**Comment by daviddarnes** [comment]
Hey there! Just to clarify, are you loading react directly into a single blog post? Seems like a bit inefficient?

**Comment by cotyhamilton** [comment]
Yes, I don’t feel that it’s inefficient, I just want to display an example of the component I wrote about. I feel like I’m missing something though, my site is built with react and was unable to use react in a post without downloading the package in the post itself, is there another way to accomplish this?

**Comment by AileenCGN** [comment]
@cotyhamilton When you opened this issue, the template stated that we use GitHub sorely for bug reports. What you are trying to do does not sound like a bug to me. Please respect our guidelines and open this topic in our forum at https://forum.ghost.org
😃

**Comment by cotyhamilton** [comment]
Just because my use case is odd doesn’t mean it isn’t a bug. It’s not a problem with ghost, it’s an issue with the service worker.
