### ISSUE TITLE
serve in /blog 

### ISSUE THREAD

**Issue by wouter-dev** [TryGhost/gatsby-starter-ghost#86]
Hello,

I'm trying to build a personal blog with this starter. I'm running into issues. I want this starter homepage to be served in /blog and build my own homepage. I tried it with changing the node slugs with /blog/ in front of it. It worked but now running into a lot of issues with this hacky method (linking from index to /blog does not work). 

Here is my repo: https://github.com/wouter-dev/Amai

Is there someone who can explain to me how to add a index page to this starter and change the current index to blog.js?

**Comment by daviddarnes** [comment]
Hey @wouter-dev 👋 This doesn't sound like a bug, which is what these GitHub issues are for, but a question about how to use the starter. Please check out our forum for assistance or open a new topic with your query: https://forum.ghost.org/c/help
