### ISSUE TITLE
Why there're not ssr-like code in page source?

### ISSUE THREAD

**Issue by zdrock** [TryGhost/gatsby-starter-ghost#94]
in page source i see code like that: 
![Screenshot (101)](https://user-images.githubusercontent.com/13319110/69894376-999bd380-1327-11ea-9c6f-c3e3dcf34ff7.png)
but after reload it displays full html page, it really confused me

**Comment by daviddarnes** [comment]
Hey! This is how Gatsby works. Viewing source will only show you the empty index.html file before it's been populated by JavaScript. If you load the page without JavaScript turned on you'll see the static server side HTML come down, then you'll be able to view source and see all the HTML of the page
<img width="1680" alt="Screenshot 2019-11-30 at 13 49 02" src="https://user-images.githubusercontent.com/1177460/69901349-430ab580-1378-11ea-8946-477ddfcc5554.png">
