### ISSUE TITLE
How can i get plaintext? 

### ISSUE THREAD

**Issue by zdrock** [TryGhost/gatsby-starter-ghost#95]
Moving from mansonry theme to Gatsby Ghost and the problem arised in plain text query, there're text with markdown, carriage returns, images inside [ ], etc

**Comment by AileenCGN** [comment]
Hey @zdrock   👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://ghost.org/docs), our [theme API](https://ghost.org/docs/api), or our [public API](https://ghost.org/docs/api). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
