### ISSUE TITLE
Update `sharp` resolution to `0.23.4`

### ISSUE THREAD

**Issue by thomb** [TryGhost/gatsby-starter-ghost#97]
### Issue Summary

When running `yarn install` on macOS the install crashes when attempting to build the version of `sharp` specific in the package.json.

Updating this to the most recent version - `0.23.4` - resolve the build issues

### To Reproduce

Clone the repo on a system matching the below tech specs and run `yarn install`

### Technical details:

* Ghost Version: N/A
* Gatsby Version:2.17.15  
* Node Version: v13.5.0
* OS: MacOS 10.14.6 (18G1012)

**Comment by daviddarnes** [comment]
Thanks for letting us know @thomb, this has been fixed
