### ISSUE TITLE
Not able to add Bootstrap in production

### ISSUE THREAD

**Issue by far11ven** [TryGhost/gatsby-starter-ghost#98]
### Issue Summary

Trying to add Bootrap 4.x into the starter template like below, which works fine in development env but gives consequent error:
![image](https://user-images.githubusercontent.com/26922130/72367953-20174380-3723-11ea-8b8b-3bea0d5ed65b.png)

Error:
![image](https://user-images.githubusercontent.com/26922130/72368017-4341f300-3723-11ea-889a-f2dbb9dca1a6.png)

### To Reproduce

1. add following lines to components/common/index.js after adding dependencies using `npm i bootstrap jquery popper.js`:
```
import "bootstrap/dist/css/bootstrap.min.css";
import $ from "jquery";
import Popper from "popper.js";
import "bootstrap/dist/js/bootstrap.bundle.min";
```
2. try running `gatsby build`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.2.0
* Gatsby CLI version: 2.8.26
* Gatsby version: 2.13.45
* Node Version: 12.10.0
* OS: windows

**Comment by daviddarnes** [comment]
This isn’t a bug but a development query, you’re better off asking in our community forum where others also using this starter can help https://forum.ghost.org/ 🙂

**Comment by far11ven** [comment]
Found a way to add Bootstrap and related dependency with gatsby is adding them in ```gatsby-browser.js``` like following:

**Step 1:** Run `npm i bootstrap jquery popper.js`

**Step 2:** In ```gatsby-browser.js``` add following imports

    import "bootstrap/dist/css/bootstrap.min.css";
    import "jquery/dist/jquery.min.js";
    import "popper.js/dist/popper.min";
    import "bootstrap/dist/js/bootstrap.min.js";


>*Note:* if `gatsby-browser.js` is already present and contains ES5 code, then that needs to be converted to ES6 first
